#!/bin/bash
# Backlink Quick Start Checklist
# Week 1 Tasks - 1.5 hours total

echo "🔗 VIETSTRIX BACKLINK QUICK START"
echo "=================================="
echo ""
echo "✅ Task 1: Link GBP to Website (2 min)"
echo "   URL: https://business.google.com"
echo "   Action: Edit profile → Contact → Website"
echo "   Enter: https://www.vietstrix.com"
echo ""
echo "✅ Task 2: Create Clutch Profile (30 min)"
echo "   URL: https://clutch.co/profile/create"
echo "   Category: Web Development"
echo "   Add: Projects, team, services"
echo ""
echo "✅ Task 3: Submit to Hotfrog Vietnam (15 min)"
echo "   URL: https://vn.hotfrog.com/add-your-business"
echo "   Use NAP: docs/BACKLINK-STRATEGY.md (line 165)"
echo ""
echo "✅ Task 4: Create GoodFirms Profile (20 min)"
echo "   URL: https://www.goodfirms.co/get-listed"
echo "   Category: Web Development Services"
echo ""
echo "✅ Task 5: Pin GitHub Repos (10 min)"
echo "   URL: https://github.com/vietstrixvn"
echo "   Pin: Top 3 projects"
echo "   Add: Website link to README"
echo ""
echo "📊 RESULT: 5 high-quality backlinks"
echo "⏱️  TOTAL TIME: ~1.5 hours"
echo ""
echo "📖 Full guide: docs/BACKLINK-STRATEGY.md"
